import { Switch } from "antd"
import { BsFillPersonCheckFill } from "react-icons/bs"
import UserManagmentAllFilter from "./UserManagmentAllFilter";
import "./Style/UserManagement.css";

const UserTbody = [
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Sohil Kazi",
        email: "Sohil@gmail.com",
        contactNumber: "9658712535",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Vikas Kumar",
        email: "Vikas@gmail.com",
        contactNumber: "9632541235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Faizan Pathan",
        email: "Faizan@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Naushad Ali",
        email: "Naushad@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
    {
        id: "612020",
        userName: "Rohit Sindhi",
        email: "Rohit@gmail.com",
        contactNumber: "9658741235",
        role: "Team Lead",
        status: true,
    },
        
]
export default UserTbody;
